# Generated by Django 6.0.7 on 2026-08-07 12:12

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='letters/%Y/%m/')),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('WITH_DIRECTOR', 'With Director'), ('WITH_MINISTER', 'With Minister'), ('WITH_EMPLOYEE', 'With Employee'), ('COMPLETE', 'Complete')], default='DRAFT', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters_created', to=settings.AUTH_USER_MODEL)),
                ('current_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters_holding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['current_holder'], name='letters_let_current_f57b1d_idx'), models.Index(fields=['status'], name='letters_let_status_a9a39d_idx')],
            },
        ),
    ]
